language: cpp

matrix:
   include:
      - env: PLATFORM=linux RELEASE=true
        os: linux
        dist: trusty
        sudo: required

      - env: PLATFORM=linux RELEASE=false QMAKESPEC=linux-clang
        os: linux
        dist: trusty
        sudo: required

      - env: PLATFORM=mac RELEASE=true
        os: osx

      - env: PLATFORM=windows RELEASE=true BITS=32
        os: linux
        dist: trusty
        sudo: required

      - env: PLATFORM=windows RELEASE=true BITS=64
        os: linux
        dist: trusty
        sudo: required

before_install:
   - source ./build/${PLATFORM}/requirement.sh

install:
   - qmake -config release
   - make

script:
   - source ./build/${PLATFORM}/test.sh

before_deploy:
   - source ./build/${PLATFORM}/package.sh

deploy:
   provider: releases
   api_key:
      secure: rzRkiUMn5Wym/anYDQ2HdNg34qt2h3CrU/K3XU5dTQfcuZg6y0Ar0qml8PhvU/fLiHX5zlpeNW8NbtWHpVS4RfUJPfnrfbv1YbBzeAvp5iFmkhaH0f0LpOyvgYy5Q2O5ofr5BS+KSD/epYRzuSCwrQUwHYn2iE2mniKC+7q8hquL7UP0Q8dM6YHdGxTrUyLecNY4LoMYYIdYU5Kw0Z4w8YMbLHY3sbEPbZI114VoFQz4s6K7Qi/FN2Hnvc3ENH3YMffpDewvn2fm483TsHKnUMztwwhGZlo+kmxKflUNygGLDA84hIQZrrXehJk1WmOcx7fPeVIH6XccZEuqu3Mg2Ly1AM3xs2bxpFCojGBvf1FGqMRfXC5o5O4MXdiV8gEqSBC+1OqQB9EOI8XPbbgsnC03djnKkKIU7eKqY/J0NGKZUtfqcfqTcqbrr7SopQUWQlvyxZjUtSEYi9HADoizeWHc4Uh0DcS8zQ52yjrP/I5pwuRLDtLk9+6kipqcpWHadFIaMyLy8LUjaVAPbwttKPfKrnAr2A3f2UqfdDXb859W6FR39Sg1D3iGYrNsNQvR3R/BVChtf7SgdU/bNMECVaP3noOJz71ccoJQBqM1QcC1m2rNEUqpBbxSar8po7NGX1w3h3/hdyhqRYGGlAz6situp1SQKGfE3DvB7lL0WWY=
   file: "$(ls localshare-${PLATFORM}*)"
   skip_cleanup: true
   on:
      repo: lereldarion/localshare
      tags: true
      condition: $RELEASE = true
