language: cpp

matrix:
   include:
      - env: PLATFORM='linux'
        os: linux
        dist: trusty
        sudo: required

      - env: PLATFORM='mac'
        os: osx
        osx_image: xcode7.2

before_install:
   - source ./build/${PLATFORM}/requirement.sh

install:
   - qmake
   - make

script:
   - echo "Ok"
   - ls -l

deploy:
   provider: releases
   api_key: "$GH_API_KEY"
   skip_cleanup: true
   on:
      tags: true
