######################################################################
# Automatically generated by qmake (2.01a) sam. juin 18 02:38:53 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += common.h localshare.h sendWindow.h trayIcon.h udpDiscovery.h
SOURCES += common.cpp main.cpp sendWindow.cpp trayIcon.cpp udpDiscovery.cpp
